### ISSUE TITLE
CSS rules involving children selectors not applied

### ISSUE THREAD

**Issue by lebolo** [exupero/saveSvgAsPng#13]
I have my SVG element contained within a `<div class="bar-chart-container">` since I have multiple SVG elements on the same page, apply different CSS rules to each, and save them individually.

Therefore, my CSS looks like

``` css
.bar-chart-container {
    font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;
}
.bar-chart-container .x-axis text {
    text-rendering: optimizeLegibility;
    font-size: 12px;
}
```

and so on. However, these aren't being applied when I save as a PNG. Previously, I noticed that `dom.querySelectorAll(...)` would return an empty array (because the clone SVG element doesn't know it's a child of `.bar-chart-container`?). I tried it with your latest commit (6c25e57e6e9e5afae927d68ec663c4a0fe13abb2) and it obviously still doesn't work.

Am I doing something wrong? I was thinking of either adding some type of prefix option to the `styles(dom)` method or maybe adding classes to the clone (may not work)?

Was wondering if you had any suggestions or insight on how to solve my problem?

I set up a [jsFiddle](http://jsfiddle.net/lebolo/L530ucw2/) for testing purposes.
